spring:
  application:
    name: cloudnest

  datasource:
    url: jdbc:postgresql://localhost:5432/cloudnest
    username: postgres
    password: Befeelg15!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true